
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather_app_production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keydb:
    image: eqalpha/keydb:latest
    restart: always
    command: --active-replica yes --multi-master no --port 6379
    volumes:
      - keydb_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/weather_app_production
      - REDIS_URL=keydb://keydb:6379/0
    volumes:
      - .:/rails

volumes:
  postgres_data:
  keydb_data:
